server:
  port: 85
urls:
  account-service: http://account-service:8080/account
  classifier-service: http://classifier-service:8080/classifier
  user-service: http://user-service:8080/user/login
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/telegram-service
    username: root
    password: root
jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
temp-storage:
  cleaning-rate: 1800000
telegram:
  api-url: https://api.telegram.org/
  webhook-path: ${TELEGRAM_WEBHOOK_PATH}
  bot-name: ${TELEGRAM_BOT_NAME}
  bot-token: ${TELEGRAM_BOT_TOKEN}
logging:
  file:
    telegram.log
