server:
  port: 80
urls:
  account-service: http://localhost:8080/account
  classifier-service: http://localhost:8081/classifier
  user-service: http://localhost:8090/public/login
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/telegram-service
    username: postgres
    password: 111
jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
temp-storage:
  cleaning-rate: 1800000
telegram:
  api-url: https://api.telegram.org/
  webhook-path: https://b2e7-37-214-60-58.eu.ngrok.io
  bot-name: ${TELEGRAM_BOT_NAME}
  bot-token: ${TELEGRAM_BOT_TOKEN}