urls:
  account-service: http://account-service:8080/account
  classifier-service: http://classifier-service:8080/classifier
  mail-service: http://mail-service:8080/mail
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://db:5432/mail-scheduler-service
    username: root
    password: root
  quartz:
    job-store-type: jdbc
    overwrite-existing-jobs: true
    jdbc:
      initialize-schema: never
      platform: postgres
    properties:
      org.quartz.jobStore.driverDelegateClass: "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
      org.quartz.jobStore.tablePrefix: "quartz.QRTZ_"
