urls:
  account-service: http://account-service:8080/account
  classifier-service: http://classifier-service:8080/classifier
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/report-service
    username: root
    password: root
minio:
  bucket.name: report
  access.key: 9Z939G61IPEV0WFHWIW1
  access.secret: krPc7XIcvXPCGnZpX1BtMnmWr4OaTzXqsH+50Jd6
  url: http://minio:9000/