urls:
  classifier-service: http://classifier-service:8080/classifier
balance-update-rate: 10000
spring:
  jpa:
    database: POSTGRESQL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/account-service
    username: root
    password: root