server:
  port: 8080
urls:
  classifier-service: http://localhost:8081/classifier
balance-update-rate: 30000
spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/account-service
    username: postgres
    password: 111
  mvc:
    view:
      prefix: /views/
      suffix: .jsp